name: Create Resources

on:
  workflow_dispatch: {}    

permissions:
  id-token: write
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::738678806999:role/GitHubActionsTerraformRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform State
        run: terraform state list

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        
      - name: Terraform Apply 
        run: terraform apply -auto-approve