name: Destory Resources

on:
  schedule:
    - cron: '0 21 * * *'  # 21:00 UTC = 10pm UK time (BST, Mar-Oct). Becomes 9pm UK during GMT (Oct-Mar).
  workflow_dispatch: {}    

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::738678806999:role/GitHubActionsTerraformRole
          aws-region: eu-west-1

      - name: Setup Terraform]
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Destroy (EC2 + volumes only)
        run: |
          terraform apply -auto-approve \
            -target=module.instance_network \
            -target=module.ec2_instance_alpha \
            -target=aws_ami_from_instance.alpha_custom_ami \
            -target=aws_instance.instance