name: Terraform CI/CD
# on:
#   push:
#     branches: [main]
on:
  workflow_dispatch: {}    

permissions:
  id-token: write
  contents: read

jobs:
  validate-plan-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::738678806999:role/GitHubActionsTerraformRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        
      - name: Terraform Apply 
        run: terraform apply -auto-approve